import { createContext, useContext, useMemo, useState, type ReactNode } from "react";

export type LanguageCode = "en" | "ta" | "hi" | "te";

type OnboardingCopy = { eyebrow: string; title: string; body: string; voiceTab: string; manualTab: string; tapToSpeak: string; listening: string; stopExtract: string; sampleDemo: string; aiProfile: string; manualProfile: string; reviewTitle: string; manualTitle: string; pending: string; name: string; phone: string; trade: string; experience: string; locality: string; baseRate: string; submit: string; submitting: string; languageHint: string; recordingStarted: string; voiceDetected: string; noSpeech: string; processing: string };
type Copy = { greeting: string; citizen: string; worker: string; admin: string; customerWorkspace: string; trustedHelp: string; trustedBody: string; services: string; serviceNetwork: string; findWorker: string; search: string; liveResults: string; matches: string; emergency: string; activeWard: string; future: string; home: string; language: string; onboarding: OnboardingCopy };

const COPY: Record<LanguageCode, Copy> = {
  en: { greeting: "Good morning", citizen: "Citizen View", worker: "Worker Passbook", admin: "PACS Admin", customerWorkspace: "Customer workspace · Gandhipuram", trustedHelp: "Trusted help, close to home.", trustedBody: "Choose a service to see live PACS-verified workers, transparent fair pricing, and their location on the cooperative map.", services: "What can we help with?", serviceNetwork: "Cooperative service network", findWorker: "Find a verified worker for", search: "Search live roster", liveResults: "Live results", matches: "cooperative matches", emergency: "Emergency Service", activeWard: "Live in your ward", future: "Phase 2 expansion", home: "Home", language: "Language", onboarding: { eyebrow: "COOPERATIVE MEMBER JOURNEY · PACS", title: "Bring your skills to the network.", body: "A focused voice-first registration flow for Tamil, Hindi, Telugu, and English-speaking skilled workers.", voiceTab: "Voice registration", manualTab: "Or Fill Manually", tapToSpeak: "Tap to Speak (Tamil / Hindi / English / Telugu)", listening: "Listening", stopExtract: "Stop & Extract Profile", sampleDemo: "Sample Voice Demo", aiProfile: "AI-EXTRACTED PROFILE", manualProfile: "Manual worker profile", reviewTitle: "Review before PACS submission", manualTitle: "Enter details before PACS submission", pending: "PENDING VERIFICATION", name: "Name", phone: "Phone", trade: "Trade", experience: "Experience (years)", locality: "Locality", baseRate: "Base rate (INR)", submit: "Submit to PACS Society", submitting: "Submitting to PACS…", languageHint: "Voice registration supports Tamil, Hindi, Telugu, and English", recordingStarted: "Speak your name, trade, experience, and locality.", voiceDetected: "Voice Detected", noSpeech: "Listening... (Speak now)", processing: "Gemini 2.5 Flash is extracting your profile…" } },
  ta: { greeting: "காலை வணக்கம்", citizen: "குடிமக்கள் பார்வை", worker: "தொழிலாளர் பாஸ்புக்", admin: "PACS நிர்வாகம்", customerWorkspace: "வாடிக்கையாளர் பணியிடம் · காந்திபுரம்", trustedHelp: "உங்கள் வீட்டிற்கு அருகில் நம்பகமான உதவி.", trustedBody: "நேரடி PACS சரிபார்க்கப்பட்ட தொழிலாளர்கள், வெளிப்படையான நியாய விலை மற்றும் வரைபட இருப்பிடத்தைப் பார்க்க சேவையைத் தேர்ந்தெடுக்கவும்.", services: "எவ்வாறு உதவலாம்?", serviceNetwork: "கூட்டுறவு சேவை வலையமைப்பு", findWorker: "சரிபார்க்கப்பட்ட தொழிலாளரைத் தேடுங்கள்", search: "நேரடி பட்டியலைத் தேடுங்கள்", liveResults: "நேரடி முடிவுகள்", matches: "கூட்டுறவு பொருத்தங்கள்", emergency: "அவசர சேவை", activeWard: "உங்கள் வார்டில் உள்ளது", future: "கட்டம் 2 விரிவாக்கம்", home: "முகப்பு", language: "மொழி", onboarding: { eyebrow: "கூட்டுறவு உறுப்பினர் பயணம் · PACS", title: "உங்கள் திறன்களை நெட்வொர்க்கிற்கு கொண்டு வாருங்கள்.", body: "தமிழ், இந்தி, தெலுங்கு மற்றும் ஆங்கிலம் பேசும் திறமையான தொழிலாளர்களுக்கான குரல் வழி பதிவு முறை.", voiceTab: "குரல் பதிவு", manualTab: "அல்லது கைமுறையாக நிரப்பவும்", tapToSpeak: "பேச தட்டவும் (தமிழ் / இந்தி / ஆங்கிலம் / தெலுங்கு)", listening: "கேட்கிறது", stopExtract: "நிறுத்தி விவரங்களைப் பெறவும்", sampleDemo: "குரல் டெமோ", aiProfile: "AI கண்டறிந்த விவரங்கள்", manualProfile: "கைமுறை தொழிலாளர் விவரம்", reviewTitle: "PACS சமர்ப்பிப்பிற்கு முன் சரிபார்க்கவும்", manualTitle: "PACS சமர்ப்பிப்பிற்கு முன் விவரங்களை உள்ளிடவும்", pending: "சரிபார்ப்பு நிலுவையில் உள்ளது", name: "பெயர்", phone: "தொலைபேசி எண்", trade: "தொழில்", experience: "அனுபவம் (ஆண்டுகள்)", locality: "பகுதி / இருப்பிடம்", baseRate: "அடிப்படை கட்டணம் (ரூ)", submit: "PACS சங்கத்தில் சமர்ப்பிக்கவும்", submitting: "PACS-க்கு சமர்ப்பிக்கப்படுகிறது…", languageHint: "தமிழ், இந்தி, தெலுங்கு மற்றும் ஆங்கில குரல் பதிவை ஆதரிக்கிறது", recordingStarted: "உங்கள் பெயர், தொழில், அனுபவம் மற்றும் பகுதியைக் கூறுங்கள்.", voiceDetected: "குரல் கண்டறியப்பட்டது", noSpeech: "கேட்கிறது... (இப்போது பேசுங்கள்)", processing: "Gemini 2.5 Flash உங்கள் விவரங்களைப் பெறுகிறது…" } },
  hi: { greeting: "सुप्रभात", citizen: "नागरिक दृश्य", worker: "वर्कर पासबुक", admin: "PACS प्रशासन", customerWorkspace: "ग्राहक कार्यक्षेत्र · गांधीपुरम", trustedHelp: "घर के पास भरोसेमंद सहायता।", trustedBody: "PACS-सत्यापित श्रमिक, पारदर्शी उचित मूल्य और सहकारी मानचित्र पर स्थान देखने के लिए सेवा चुनें।", services: "हम आपकी कैसे मदद कर सकते हैं?", serviceNetwork: "सहकारी सेवा नेटवर्क", findWorker: "सत्यापित श्रमिक खोजें", search: "लाइव रोस्टर खोजें", liveResults: "लाइव परिणाम", matches: "सहकारी मिलान", emergency: "आपातकालीन सेवा", activeWard: "आपके वार्ड में उपलब्ध", future: "चरण 2 विस्तार", home: "होम", language: "भाषा", onboarding: { eyebrow: "सहकारी सदस्य यात्रा · PACS", title: "अपने कौशल को नेटवर्क से जोड़ें।", body: "तमिल, हिंदी, तेलुगु और अंग्रेजी बोलने वाले कुशल श्रमिकों के लिए वॉयस-फर्स्ट पंजीकरण।", voiceTab: "वॉयस पंजीकरण", manualTab: "या मैन्युअल रूप से भरें", tapToSpeak: "बोलने के लिए टैप करें (तमिल / हिंदी / अंग्रेजी / तेलुगु)", listening: "सुन रहा है", stopExtract: "रोकें और प्रोफ़ाइल निकालें", sampleDemo: "वॉयस डेमो", aiProfile: "AI द्वारा निकाली गई प्रोफ़ाइल", manualProfile: "मैन्युअल श्रमिक प्रोफ़ाइल", reviewTitle: "PACS सबमिशन से पहले समीक्षा करें", manualTitle: "PACS सबमिशन से पहले विवरण भरें", pending: "सत्यापन लंबित", name: "नाम", phone: "फ़ोन नंबर", trade: "व्यवसाय / ट्रेड", experience: "अनुभव (वर्ष)", locality: "इलाका", baseRate: "मूल दर (रुपये)", submit: "PACS समिति में जमा करें", submitting: "PACS में जमा किया जा रहा है…", languageHint: "तमिल, हिंदी, तेलुगु और अंग्रेजी वॉयस पंजीकरण समर्थित", recordingStarted: "अपना नाम, ट्रेड, अनुभव और इलाका बोलें।", voiceDetected: "आवाज़ पहचानी गई", noSpeech: "सुन रहा है... (अब बोलें)", processing: "Gemini 2.5 Flash आपकी प्रोफ़ाइल निकाल रहा है…" } },
  te: { greeting: "శుభోదయం", citizen: "పౌరుల వీక్షణ", worker: "కార్మిక పాస్‌బుక్", admin: "PACS నిర్వాహకుడు", customerWorkspace: "కస్టమర్ వర్క్‌స్పేస్ · గాంధీపురం", trustedHelp: "మీ ఇంటికి దగ్గరగా నమ్మకమైన సహాయం.", trustedBody: "PACS ధృవీకరించిన కార్మికులు, పారదర్శక ధరలు మరియు మ్యాప్ స్థానాలను చూడటానికి సేవను ఎంచుకోండి.", services: "మేము ఎలా సహాయపడగలం?", serviceNetwork: "సహకార సేవా నెట్‌వర్క్", findWorker: "ధృవీకరించిన కార్మికుడిని కనుగొనండి", search: "లైవ్ రోస్టర్ శోధన", liveResults: "లైవ్ ఫలితాలు", matches: "సహకార సరిపోలికలు", emergency: "అత్యవసర సేవ", activeWard: "మీ వార్డులో అందుబాటులో ఉంది", future: "దశ 2 విస్తరణ", home: "హోమ్", language: "భాష", onboarding: { eyebrow: "సహకార సభ్యుల ప్రయాణం · PACS", title: "మీ నైపుణ్యాలను నెట్‌వర్క్‌కు తీసుకురండి.", body: "తమిళం, హిందీ, తెలుగు మరియు ఇంగ్లీష్ మాట్లాడే నైపుణ్య కార్మికుల కోసం వాయిస్ ఆధారిత నమోదు.", voiceTab: "వాయిస్ నమోదు", manualTab: "లేదా మాన్యువల్‌గా నింపండి", tapToSpeak: "మాట్లాడటానికి ట్యాప్ చేయండి (తమిళం / హిందీ / ఇంగ్లీష్ / తెలుగు)", listening: "వింటోంది", stopExtract: "ఆపి ప్రొఫైల్‌ను సేకరించండి", sampleDemo: "వాయిస్ డెమో", aiProfile: "AI సేకరించిన వివరాలు", manualProfile: "మాన్యువల్ కార్మిక వివరాలు", reviewTitle: "PACS సమర్పణకు ముందు సమీక్షించండి", manualTitle: "PACS సమర్పణకు ముందు వివరాలు నమోదు చేయండి", pending: "ధృవీకరణ పెండింగ్‌లో ఉంది", name: "పేరు", phone: "ఫోన్ నంబర్", trade: "వృత్తి", experience: "అనుభవం (సంవత్సరాలు)", locality: "ప్రాంతం", baseRate: "ప్రాథమిక రేటు (రూ)", submit: "PACS సంఘానికి సమర్పించండి", submitting: "PACSకి సమర్పిస్తోంది…", languageHint: "తమిళం, హిందీ, తెలుగు మరియు ఇంగ్లీష్ వాయిస్ నమోదుకు మద్దతు", recordingStarted: "మీ పేరు, వృత్తి, అనుభవం మరియు ప్రాంతాన్ని చెప్పండి.", voiceDetected: "వాయిస్ గుర్తించబడింది", noSpeech: "వింటోంది... (ఇప్పుడు మాట్లాడండి)", processing: "Gemini 2.5 Flash మీ ప్రొఫైల్‌ను సేకరిస్తోంది…" } },
};

const TRADE_LABELS: Record<LanguageCode, Record<string, string>> = {
  en: { Plumbing: "Plumbing", Electrical: "Electrical", "House Cleaning": "Cleaning", Carpentry: "Carpentry", "AC Repair": "AC Repair", Masonry: "Masonry" },
  ta: { Plumbing: "பிளம்பிங்", Electrical: "மின்சாரம்", "House Cleaning": "சுத்தம்", Carpentry: "தச்சு", "AC Repair": "ஏசி பழுது", Masonry: "கட்டிடம்" },
  hi: { Plumbing: "प्लंबिंग", Electrical: "इलेक्ट्रिकल", "House Cleaning": "सफाई", Carpentry: "बढ़ईगीरी", "AC Repair": "एसी मरम्मत", Masonry: "राजमिस्त्री" },
  te: { Plumbing: "ప్లంబింగ్", Electrical: "ఎలక్ట్రికల్", "House Cleaning": "క్లీనింగ్", Carpentry: "వడ్రంగి", "AC Repair": "ఏసీ రిపేర్", Masonry: "మేసన్రీ" },
};

const LanguageContext = createContext<{ language: LanguageCode; setLanguage: (language: LanguageCode) => void; t: Copy; trade: (service: string) => string } | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) { const [language, setLanguage] = useState<LanguageCode>(() => { const stored = sessionStorage.getItem("ubiquity.language") as LanguageCode | null; return stored && ["en", "ta", "hi", "te"].includes(stored) ? stored : "en"; }); const update = (next: LanguageCode) => { setLanguage(next); sessionStorage.setItem("ubiquity.language", next); }; const value = useMemo(() => ({ language, setLanguage: update, t: COPY[language], trade: (service: string) => TRADE_LABELS[language][service] || service }), [language]); return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>; }
export function useLanguage() { const value = useContext(LanguageContext); if (!value) throw new Error("useLanguage must be used inside LanguageProvider"); return value; }
